<a href="https://colab.research.google.com/github/dtype2100/Python/blob/master/argmax1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.arange(6).reshape(2,3) + 10

In [ ]:
a

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
np.argmax(a)

5

In [ ]:
np.argmax(a, axis=0)

array([1, 1, 1])

In [ ]:
np.argmax(a, axis=1)

array([2, 2])