<a href="https://colab.research.google.com/github/dtype2100/Python/blob/master/array_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **다양한 방식으로 array 생성하기 **

In [ ]:
import numpy as np

In [ ]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
b = np.array([[2, 3, 4], [5, 6, 7]])
b

array([[2, 3, 4],
       [5, 6, 7]])

In [ ]:
c = np.array([(1, 2, 3), (4, 5,  6)])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
d = np.zeros((3, 4))
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
e = np.zeros([3, 4])
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
f = np.ones((2, 3, 1), dtype=np.int16)
f

array([[[1],
        [1],
        [1]],

       [[1],
        [1],
        [1]]], dtype=int16)

In [ ]:
g = np.ones((2, 3, 2), dtype=np.int16)
g

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int16)

In [ ]:
h = np.ones((2, 3, 3), dtype=np.int16)
h

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [ ]:
i = np.ones((2, 3, 4), dtype=np.int16)
i

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [ ]:
j = np.ones((2, 3, 5), dtype=np.int16)
j

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)

In [ ]:
k = np.ones((2, 3, 6), dtype=np.int16)
k

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]], dtype=int16)

# empty: 랜덤하게 메모리 상태에 따라 달라지는 array 생성

In [ ]:
np.empty((2, 3))

array([[4.65755326e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

# **10~30까지 5의 배수 출력**

In [ ]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

# 0~1, 0~2, 0~3 사이 0.3의 배수 출력

In [ ]:
np.arange(0, 1, 0.3)

array([0. , 0.3, 0.6, 0.9])

In [ ]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [ ]:
np.arange(0, 3, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7])

In [ ]:
from numpy import pi

In [ ]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [ ]:
np.linspace(2, 3, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [ ]:
np.linspace(0, 2, 9) 

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
x = np.linspace(0, 2 * pi, 100)  
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652